# Generated by Django 2.2.4 on 2020-05-16 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0003_remove_ninjas_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjas',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_uploaded', to='dojo_ninjas_app.dojos'),
        ),
    ]
