# Generated by Django 2.2.4 on 2020-05-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0006_auto_20200516_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo',
        ),
    ]
