# Generated by Django 2.2.4 on 2020-05-17 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0008_ninja_dojo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='dojo',
        ),
        migrations.AddField(
            model_name='ninja',
            name='dojos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dojos', to='dojo_ninjas_app.dojos'),
        ),
    ]
