# Generated by Django 2.2.4 on 2020-05-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(max_length=255),
        ),
    ]
