# Generated by Django 2.2.4 on 2020-05-15 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloApp', '0002_auto_20200514_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
    ]
