# Generated by Django 2.2.4 on 2020-05-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_books_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
