# Generated by Django 2.2.4 on 2020-05-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0007_auto_20200517_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(null=True, related_name='authors', to='books_authors_app.books'),
        ),
    ]
