# Generated by Django 2.2.4 on 2020-05-18 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0009_remove_authors_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(null=True, related_name='authors', to='books_authors_app.books'),
        ),
    ]
