# Generated by Django 2.2.4 on 2020-05-18 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0017_authors_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books_authors',
        ),
    ]
