# Generated by Django 2.2.4 on 2020-05-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0018_delete_books_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='authors',
            name='books',
        ),
    ]
