# Generated by Django 2.2.4 on 2020-05-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0023_auto_20200517_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books_authors',
        ),
    ]
