# Generated by Django 2.2.4 on 2020-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0024_delete_books_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='update',
            field=models.ManyToManyField(related_name='author', to='books_authors_app.books'),
        ),
    ]
