# Generated by Django 2.2.4 on 2020-05-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0025_auto_20200517_2220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authors',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
    ]
