# Generated by Django 2.2.4 on 2020-05-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0027_remove_author_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RenameModel(
            old_name='Book',
            new_name='books',
        ),
        migrations.AddField(
            model_name='authors',
            name='update',
            field=models.ManyToManyField(related_name='author', to='books_authors_app.books'),
        ),
    ]
