# Generated by Django 2.2.4 on 2020-05-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0028_auto_20200518_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authors',
        ),
    ]
