# Generated by Django 2.2.4 on 2020-05-19 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0029_delete_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='books',
        ),
    ]
