# Generated by Django 2.2.4 on 2020-05-20 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0003_auto_20200520_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='value',
        ),
    ]
